openapi: 3.0.3
info:
  title: Book Management API
  description: RESTful API for managing books with CRUD operations
  version: 1.0.0
  contact:
    name: API Support
    email: support@bookapi.com

servers:
  - url: http://localhost:5000/api/v1
    description: Development server

tags:
  - name: Books
    description: Operations related to book management

paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: Retrieve a list of all books in the system
      operationId: controllers.books_controller.get_books
      parameters:
        - name: title
          in: query
          description: Filter books by title (partial match)
          required: false
          schema:
            type: string
        - name: author
          in: query
          description: Filter books by author (partial match)
          required: false
          schema:
            type: string
        - name: available
          in: query
          description: Filter by availability status
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Book'
                  count:
                    type: integer
                    example: 10
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Clean Code"
        author:
          type: string
          example: "Robert C. Martin"
        publisher:
          type: string
          example: "Prentice Hall"
        quantity:
          type: integer
          example: 5

    BookInput:
      type: object
      required:
        - title
        - author
      properties:
        title:
          type: string
          example: "Clean Code"
        author:
          type: string
          example: "Robert C. Martin"
        publisher:
          type: string
          example: "Prentice Hall"
        quantity:
          type: integer
          example: 5

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: "Error message"

