from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BookInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, author=None, publisher=None, quantity=None):  # noqa: E501
        """BookInput - a model defined in OpenAPI

        :param title: The title of this BookInput.  # noqa: E501
        :type title: str
        :param author: The author of this BookInput.  # noqa: E501
        :type author: str
        :param publisher: The publisher of this BookInput.  # noqa: E501
        :type publisher: str
        :param quantity: The quantity of this BookInput.  # noqa: E501
        :type quantity: int
        """
        self.openapi_types = {
            'title': str,
            'author': str,
            'publisher': str,
            'quantity': int
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author',
            'publisher': 'publisher',
            'quantity': 'quantity'
        }

        self._title = title
        self._author = author
        self._publisher = publisher
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'BookInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookInput of this BookInput.  # noqa: E501
        :rtype: BookInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this BookInput.


        :return: The title of this BookInput.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this BookInput.


        :param title: The title of this BookInput.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this BookInput.


        :return: The author of this BookInput.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this BookInput.


        :param author: The author of this BookInput.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def publisher(self) -> str:
        """Gets the publisher of this BookInput.


        :return: The publisher of this BookInput.
        :rtype: str
        """
        return self._publisher

    @publisher.setter
    def publisher(self, publisher: str):
        """Sets the publisher of this BookInput.


        :param publisher: The publisher of this BookInput.
        :type publisher: str
        """

        self._publisher = publisher

    @property
    def quantity(self) -> int:
        """Gets the quantity of this BookInput.


        :return: The quantity of this BookInput.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this BookInput.


        :param quantity: The quantity of this BookInput.
        :type quantity: int
        """

        self._quantity = quantity
