from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Error(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, error=None):  # noqa: E501
        """Error - a model defined in OpenAPI

        :param success: The success of this Error.  # noqa: E501
        :type success: bool
        :param error: The error of this Error.  # noqa: E501
        :type error: str
        """
        self.openapi_types = {
            'success': bool,
            'error': str
        }

        self.attribute_map = {
            'success': 'success',
            'error': 'error'
        }

        self._success = success
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.  # noqa: E501
        :rtype: Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this Error.


        :return: The success of this Error.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this Error.


        :param success: The success of this Error.
        :type success: bool
        """

        self._success = success

    @property
    def error(self) -> str:
        """Gets the error of this Error.


        :return: The error of this Error.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this Error.


        :param error: The error of this Error.
        :type error: str
        """

        self._error = error
